jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: zulu
        java-version: '11'
    - continue-on-error: true
      name: Cache Gradle packages
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
      with:
        key: ${{ runner.os }}-gradle-1-${{ hashFiles('**/*.gradle') }}
        path: ~/.gradle/caches
        restore-keys: ${{ runner.os }}-gradle-1-
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Verify generated module-info
      run: ./gradlew -PjavaCompatibility=9 jar
    - continue-on-error: true
      name: Build RxJava
      run: ./gradlew build --stacktrace
    - continue-on-error: true
      name: Generate Javadoc
      run: ./gradlew javadoc --stacktrace
name: JDK 11
on:
  repository_dispatch:
    types: trigger-ga___gradle_jdk11.yml
permissions:
  contents: read
