jobs:
  validation:
    name: Validation
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
    - continue-on-error: true
      uses: gradle/wrapper-validation-action@88425854a36845f9c881450d9660b5fd46bee142
name: Validate Gradle Wrapper
on:
  repository_dispatch:
    types: trigger-ga___gradle-wrapper-validation.yml
permissions:
  contents: read
